

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresDB
    username: YourPostgresUser
    password: YourPostgresPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: 'sandbox.smtp.mailtrap.io'
    port: 2525
    username: smtpUsername
    password: smtpPassword
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  freemarker:
    template-loader-path: classpath:/templates