

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: 'sandbox.smtp.mailtrap.io'
    port: 2525
    username: ce9fe01e3310c8
    password: 1d68d8863c0c9d
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  freemarker:
    template-loader-path: classpath:/templates